services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    networks:
      - guessmoji-net
    command: flask run --host=0.0.0.0 --reload 

  frontend:
    build: 
      context: ./frontend
      target: development
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - guessmoji-net
    command: npm run start -- --host 0.0.0.0  # Use npm script with host flag

networks:
  guessmoji-net: